### ISSUE TITLE
Description and title lenght

### ISSUE THREAD

**Issue by StefanoChiodino** [ryanlewis/seo-metadata#29]
Hey, how's it going? Apparently Google now has limits on "number of pixels" rather than character for both meta title and meta description.
Ref. https://moz.com/blog/title-tag-length-guidelines-2016-edition

Is it possible to have more warnings, and maybe a much higher limit, but not stop the document from publishing?

**Comment by StefanoChiodino** [comment]
Neeevermind, didn't see you can allow long title/description in the configuration!

**Comment by ryanlewis** [comment]
Could you elaborate a little more on how Google limits its SERPs?

-- 
Ryan Lewis
ryan@wpyz.org

**Comment by StefanoChiodino** [comment]
They have changed the limits on both description and title to work on pixel
width rather than character count!
