### ISSUE TITLE
When null get error

### ISSUE THREAD

**Issue by wroughtec** [ryanlewis/seo-metadata#4]
If the I leave the title description as blank I get:
System.NullReferenceException: Object reference not set to an instance of an object.
on 1: @if (metadata.Title != null) when I am trying to use:

```
@if (metadata.Title != null)
{
    <title>@metadata.Title</title>
}else{
    <title>Company Name | @CurrentPage.Name</title>
}
@if (metadata.Description != null)
{
    <meta name="description" content="@metadata.Description" />
} else {
    <meta name="description" content="default description" />
}
@if (Model.Content.GetPropertyValue<Epiphany.SeoMetadata.SeoMetadata>("seo").NoIndex)
{
    <meta name="robots" content="noindex">
}
```

Any suggestions to get around this?

**Comment by ryanlewis** [comment]
The error is being thrown because `metadata` is null. Are you sure it is set?

```
@{
    var metadata = Model.Content.GetPropertyValue<Epiphany.SeoMetadata.SeoMetadata>("seo");
}
```

If this doesn't resolve it, could you post the full stacktrace?

**Comment by wroughtec** [comment]
That was already there here is the stacktrace:

[NullReferenceException: Object reference not set to an instance of an object.]
   ASP._Page_Views_Partials_SEO_cshtml.Execute() in SEO.cshtml:11
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +103
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +88
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +254
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer) +93
   System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection) +277
   System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName) +57
   ASP._Page_Views_Master_cshtml.Execute() in c:\Users\william.corry\Documents\Visual Studio 2013\Projects\Caxton FX Multi Currency\Caxton FX Multi Currency\Views\Master.cshtml:18
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +103
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +88
   System.Web.WebPages.<>c__DisplayClass7.<RenderPageCore>b__6(TextWriter writer) +233
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +71
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +64
   System.Web.WebPages.WebPageBase.PopContext() +246
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +95
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +254
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer) +93
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +291
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17() +23
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +245
   System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +22
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +245
   System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +22
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +176
   System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +75
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +99
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +14
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +25
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9676252
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by ryanlewis** [comment]
Did you install via Nuget or via the Umbraco package? Best guess is that `SeoMetadataPropertyValueConverter` isn't being picked up by Umbraco and so the GetPropertyValue<> call returns null.

**Comment by wroughtec** [comment]
Installed by Nuget

**Comment by ryanlewis** [comment]
Could you link to a gist of the full file?

**Comment by wroughtec** [comment]
I assume you mean the partial view its linked in:

https://gist.github.com/wroughtec/d7a87988f3302d6e20b5

Its strange as when I add data to the title save then delete the title and save the page works although the title is blank rather than using the fallback.

Ideally all the pages will have the data however I need a fallback encase a content writer forgets :(

**Comment by ryanlewis** [comment]
I think I understand what's going on here now. 

When you have the mandatory field value unticked and then you do not touch the property editor, the value will still be stored as null. I can see how this would be a problem if you use the control on a tucked away tab.

I'll release a fix to the issue shortly.

**Comment by wroughtec** [comment]
Thanks

**Comment by ryanlewis** [comment]
I have a pre-release available of this - could you try the following version? (working for me)

Run the following in Package Manager Console

```
update-package Epiphany.SeoMetadata -Source http://www.myget.org/F/epiphany
```

**Comment by wroughtec** [comment]
hmm no joy
The only way I have got it to work is check then uncheck before saving to get it to work :(

**Comment by ryanlewis** [comment]
Have you refreshed your browser cache? (try logging into backoffice with an incognito tab)

**Comment by wroughtec** [comment]
Ok seems to work for new pages republishing the entire site did not work for old pages but individual saving did thanks

**Comment by ryanlewis** [comment]
Republishing the entire site is misleading - it just refreshes the cache. Saving each page individually regenerates the cache for each page was the way to go for old pages. Glad it's sorted.
