### ISSUE TITLE
Best practices for integrating to master template

### ISSUE THREAD

**Issue by akeilox** [ryanlewis/seo-metadata#6]
Thank you for sharing this package, looking pretty good so far.
I have tried to integrate to the master template but thought of bouncing few questions off you;
a) is there a way to use the code so that it looks for "metadata" property (if defined) climbing up the tree like the way we used to do by putting underscore (ex: Model._metadata) so it looks at current page or its parent(s) until it finds defined page?

b) when i tried to use the no-follow code i keep getting exception even on the page where i captured the metadata property values;
@if (Model.Content.GetPropertyValue<Epiphany.SeoMetadata.SeoMetadata>("metadata").NoIndex)

the .NoIndex keeps returning null. Am i missing something?

cheers

**Comment by ryanlewis** [comment]
Good to hear you're liking it so far.
1. You need to call `Model.Content.GetPropertyValue<SeoMetadata>("metadata", true)` (the true tells Umbraco to search for the property recursively)
2. You'll need to use the generic version to make sure you are getting an instance of `SeoMetadata`. The standard `GetPropertyValue()` method returns an `object`

``` c#
@if (Model.Content.GetPropertyValue<SeoMetadata>("metadata").NoIndex)
{
  <h1>Go away google...</h1>
}
```

If you want to use it recursively...

``` c#
@if (Model.Content.GetPropertyValue<SeoMetadata>("metadata", true).NoIndex)
{
  <h1>Go away google...</h1>
}
```

Check out the docs [here](https://our.umbraco.org/documentation/Reference/Templating/Mvc/views).
