### ISSUE TITLE
Third level pages show an incorrect URL when the URL alias is used

### ISSUE THREAD

**Issue by ryanlewis** [ryanlewis/seo-metadata#9]

**Comment by freestyln** [comment]
Will this bug be fixed anytime soon? 
Really in need of page url for 3+ level nodes! :)

**Comment by ryanlewis** [comment]
Will try to make time for this on Monday during office hours (although I cannot promise anything, will try and get it done!)

—

**Comment by freestyln** [comment]
Thanks a lot, will be awaiting patiently!

**Comment by ryanlewis** [comment]
Resolved in ef0344425628564b7d7b96c69765a9e99b88d09d
